configfile:"config.yaml"

(PLAQUES,SAMPLES,IDS,RUNS,LANES,PAIRED,) = glob_wildcards(config["dataDirInput"]+"{plaque}/{sample}/{id}_run{run}_L{lane}_R{paire}_001.fastq.gz")


rule all:
  input:
    expand(config["dataDirOutput"]+"{plaque}/{sample}/{id}_run{run}_L{lane}_mapped.bam", zip, plaque = PLAQUES, sample = SAMPLES, id = IDS, run = RUNS, lane = LANES),


rule trimmomatic:
  input: 
    read1=config["dataDirInput"]+"{plaque}/{sample}/{id}_run{run}_L{lane}_R1_001.fastq.gz",
    read2=config["dataDirInput"]+"{plaque}/{sample}/{id}_run{run}_L{lane}_R2_001.fastq.gz"
  output:
    read1_paired=config["dataDirOutput"]+"{plaque}/{sample}/{id}_run{run}_L{lane}_R1_001_paired.fastq.gz",
    read2_paired=config["dataDirOutput"]+"{plaque}/{sample}/{id}_run{run}_L{lane}_R2_001_paired.fastq.gz",
  shell:
    """
    echo {input.read1} > {output.read1_paired}
    echo {input.read2} > {output.read2_paired}
    """

rule mapping:
  input:
    read1_paired=config["dataDirOutput"]+"{plaque}/{sample}/{id}_run{run}_L{lane}_R1_001_paired.fastq.gz",
    read2_paired=config["dataDirOutput"]+"{plaque}/{sample}/{id}_run{run}_L{lane}_R2_001_paired.fastq.gz",
  output:
    config["dataDirOutput"]+"{plaque}/{sample}/{id}_run{run}_L{lane}_mapped.bam"
  shell:
    """
    cat {input} > {output}
    """


#(DIRS,IDS,LANES,) = glob_wildcards(config["dataDirOutput"]+"{dirs}/{id}_L{lane}_mapped.bam")
#(DIRS,IDS) = glob_wildcards(config["dataDirOutput"]+"{dirs}/{id}_mapped.bam")
(IDS,LANES,) = glob_wildcards(config["dataDirOutput"]+"{id}_L{lane}_mapped.bam")

print (IDS)


rundict={}

for file_path in set(IDS):
  lanes, = glob_wildcards(config["dataDirOutput"] + file_path + "_L{lane}_mapped.bam")
  rundict[config["dataDirOutput"] + file_path]=lanes

#print (rundict)

#print (DIRS)
#print (IDS)
#print (LANES)
